openapi: 3.0.0
info:
  title: Rest API - Yoga (Express JS)
  description: API untuk manajemen produk dengan Authentication.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local Server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /auth/token:
    post:
      summary: Mendapatkan Access Token (JWT)
      description: Masukkan API Key dan Secret Key di Header.
      security: [] # Public endpoint
      parameters:
        - in: header
          name: x-api-key
          schema:
            type: string
          required: true
        - in: header
          name: x-api-secret
          schema:
            type: string
          required: true
      responses:
        200:
          description: Berhasil mendapatkan token
        401:
          description: Credential salah

  /products:
    get:
      summary: Mengambil semua data produk
      responses:
        200:
          description: List produk
    post:
      summary: Membuat produk baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                description:
                  type: string
      responses:
        201:
          description: Produk berhasil dibuat

  /products/{id}:
    get:
      summary: Detail produk berdasarkan ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Detail produk
        404:
          description: Produk tidak ditemukan
    put:
      summary: Update produk
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
      responses:
        200:
          description: Update berhasil
    delete:
      summary: Hapus produk
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Hapus berhasil